#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

# Evaluate enviornment setup scripts
if [ -d ~/etc/env.d ]; then
    for env_script in `ls ~/etc/env.d` ; do
        . ~/etc/env.d/$env_script
    done
fi

run() {
  [ -x $1 ] && $1 $oldrev $newrev
}

echo files changed: $(git diff $oldrev $newrev --diff-filter=ACDMR --name-only | wc -l)

umask 002

git submodule sync && git submodule update --init --recursive

run deploy/update_plone || exit $?

if [ -x deploy/notify_errbit ]; then
    deploy/notify_errbit || exit $?
fi
